
version: "3"
services:
  node_backend:
    container_name: "node_backend"
    build: ./node_backend/
    ports:
      - "5000:5000"
  pg:
   image: "postgres:12"
   environment: 
    - POSTGRES_PASSWORD=1994 
   container_name: "postgres"
   ports:
   - "5432:5432"
   volumes:
   # - ./pg/db_data:/var/lib/postgresql/data    mounting folder for db  on linux
   - /var/lib/postgresql/data # for windows respectively

  react_frontend:
    container_name: "react_frontend"
    build: ./react_frontend/
    ports:
      - "3000:3000"
    stdin_open: true 